In [1]:
def divide():
    y=5/0
    print(y)
try:
    divide()
except ZeroDivisionError:
    print("Cannot divide by zero.")

Cannot divide by zero.


In [2]:
s=["Americans","Indians"]
v=["play","watch"]
o=["Baseball","Cricket"]
i=0
j=0
k=0
for i in range(len(s)):
    for j in range(len(v)):
        for k in range(len(o)):
            print(s[i]+" "+v[j]+" "+o[k]+".")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [13]:
def GPMatrix(l,N):
    import numpy as np
    r=[]
    for num in l:
        y=[]
        i=0
        while i<N:
            y.append(num**(N-i-1))
            i=i+1
        r.append(y)
    print(np.asarray(r))
    

li=[1,2,3,4,5]
GPMatrix(li,4) 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
